services:
  frontend:
    build: ./frontend
    ports: 
      - 4200:80

  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - NODE_ENV=
      - PASSWORD_SECRET=
      - TOKEN_SECRET=
      - DB_DIALECT=
      - DB_HOST=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_NAME=
      - SMTP_HOST=
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_SECURE=
      - INITIALIZE=

  database:
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DATABASE=
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      
volumes:
  postgres_volume: